# Created 2021-06-15 Tue 18:21
#+OPTIONS: H:3 num:nil toc:t \n:nil ::t |:t ^:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+TITLE: Org Internet Relay Chat (IRC)
#+AUTHOR: Worg people
#+startup: align fold nodlcheck hidestars oddeven lognotestate
#+seq_todo: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+tags: Write(w) Update(u) Fix(f) Check(c)
#+language: en
#+priorities: A C B
#+category: worg
#+html_link_up: index.html
#+html_link_home: https://orgmode.org/worg/

* Internet Relay Chat (IRC)

Like many Free Software projects Org has an active IRC channel on the
Freenode IRC network. IRC is a form of real time chat with other users
who join the network and are participating in the channel.

- Org IRC channel details
  - Network :: https://freenode.net/
  - IRC Server :: chat.freenode.net
  - Channel :: #org-mode

* Nickname Registration

*UPDATE (September 2020):* We are currently experimenting with lifting
the freenode account registration requirement for =#org-mode=.  As of
now, registering an account is /not/ required for joining the channel.
If this experiment goes well, we will continue to not require an
account.  Watch this space for future updates.

Currently you must have a registered nickname with Freenode to join
the Org channel.

Please see instructions at: https://freenode.net/kb/answer/registration

* IRC Guidelines

IRC is a highly asynchronous form of chat. If the channel is not busy,
don't be discouraged. Users come and go and watch the history.

When you join the channel, there is no need to ask whether you can ask
a question. Please ask directly what you would like to discuss, and
wait for a reply. You may wait quite some time so don't ask and quit
five minutes later.

Be polite and respect other users. Rude behavior and spam are not
tolerated.

Examples of etiquette guides from other channels:

- https://freenode.net/changuide
- https://wiki.ubuntu.com/IRC/Guidelines

Please consider using a privacy friendly paste service for posting
code, like http://bpaste.net/ .

* IRC Clients

- Emacs IRC (ERC): https://www.gnu.org/software/emacs/erc.html
- Irssi
- Freenode has a web client at: https://webchat.freenode.net/
- plenty of other clients, search for your OS and IRC client
