# Created 2021-06-15 Tue 18:23
#+OPTIONS: H:3 num:nil toc:t \n:nil ::t |:t ^:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc ':t
#+TITLE: Worg Contribution Sandbox
#+AUTHOR: Worg people
#+startup: align fold nodlcheck hidestars oddeven lognotestate
#+seq_todo: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+tags: Write(w) Update(u) Fix(f) Check(c)
#+language: en
#+category: worg
#+html_link_up: index.html
#+html_link_home: https://orgmode.org/worg/

* History
Sign your name when you make changes. Think of it as the page's guestbook. :-)
- [2010-12-05 Sun 23:59]  jrhorn424 creates the page at Bastien's suggestion.
* Tasks
** TODO Find tutorial for writing worg pages, to complete the following tasks.
** TODO Figure out how to show inactive timestamps on web page (for History).
** TODO Figure out how to link "History" in previous task to the History section above.
** DONE Fix links in Try It Out section below.
* Introduction
Bastien says "An idea: maybe have a sandbox.org file somewhere in Worg, so that
people can do 'pull' tests in here at no risk."

And, lo, it was pushed into existence.
* Try it out
Since you're here, why not see [[file:worg-about.org][how you can contribute to Worg]]. If you haven't yet done so, familiarize yourself with how you can [[file:worg-about.org::*How to use git for Worg][use git to contribute to Worg]].
