# Created 2021-06-15 Tue 18:23
#+OPTIONS: H:3 num:nil toc:t \n:nil ::t |:t ^:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+TITLE: How to edit Worg files?
#+AUTHOR: Worg people
#+startup: align fold nodlcheck hidestars oddeven lognotestate
#+seq_todo: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+tags: Write(w) Update(u) Fix(f) Check(c)
#+language: en
#+priorities: A C B
#+category: worg
#+html_link_up: index.html
#+html_link_home: https://orgmode.org/worg/

Since Worg is just starting now, these conventions are just suggestions,
not recommendations.  Please improve this.

* Conventions
** To-do keywords

Here is a table with default to-do keywords and their meaning.

| To-do keyword | Meaning                                  |
|---------------+------------------------------------------|
| TODO(t)       | Things to do                             |
| INPROGRESS(i) | Thing being in the process of being done |
| WAITING(w@)   | Tasks stuck at some point                |
| DONE(d)       | Completed task                           |
| CANCELED(c@)  | Canceled task                            |

Feel free to discuss the relevance of these keywords and propose
changes.

** Tags

: Write(w) Update(u) Fix(f) Check(c)

** Encoding
** Properties
** Link abbrevations
** Conventions about content?
Where you want to follow a documentation convention you may consider the
[[https://code.orgmode.org/bzg/org-mode/raw/master/doc/Documentation_Standards.org][Org documentation standards]].

** How rigid are these conventions?

(Suggestion: the farther from the index page you are, the more flexible
the conventions should perhaps be.)

* How do I link to other Worg files?
Links to other Worg pages should have the following format:

: [[file:index.org][Worg's home page]]


This link will converted to a relative html link on export that looks
like this:

[[file:index.org][Worg's home page]]

The filename should be a relative path. Thus, if you are creating a
link to the index from within the org-tutorials directory, you should
enter the path as follows:

: [[file:../index.org][Worg's home page]]


The easiest way to create links to files is by typing =C-c C-l= while
editing an org file. This will prompt you for both components of the
link. (Be sure to enter =file:= before the path; this indicates the
type of link.)

To enter file links more easily, you can simply type =C-u C-c C-l=. This
will allow you to locate the file using emacs' built-in completion
facilities and will automatically add the =file:= prefix.

One note of caution here: the path of the resulting link created
depends on the setting of =org-link-file-path-type=. To ensure that you
always use relative links, you can add the following to your =.emacs=
file:

#+begin_src emacs-lisp
(setq org-link-file-path-type 'relative)
#+end_src

See also: [[info:org#External%20links][External links]] in the Org manual for details on how to link
to a specific location within another Worg page.

* What is the default header for new files?

You can find a default header here: [[file:worg-header.org][worg-header.org]]

* How do I create a file?

Just create it.  Before committing changes in Worg, make sure you add
the file to the repository index with =git add *.org=.

* What about dynamic blocks

If you are using dynamic blocks in Worg, please don't forget to add the
relevant code in the [[file:code/elisp/worg.el][code/elisp/worg.el]] file.  See for example the dynamic
block for the timestamp in the [[file:index.org][index]] page.

* What about macros

If you are using macros, please add them to =macros.setupfile=.

* How do I link to the Org version of the file?

The raw Org versions of the files are published [[https://orgmode.org/worg/sources/][here]].
