# Created 2021-06-15 Tue 18:23
#+OPTIONS: H:3 num:nil toc:1 \n:nil @:t ::t |:t ^:{} -:t f:t *:t TeX:t LaTeX:nil skip:t d:nil tags:not-in-toc
#+TITLE: Org-Mode Survey Results - 2013
#+AUTHOR: Mike McLean
#+language: en

* Introduction

#+index: Customization!Survey-2013

This file serves as a placeholder for the 2013 Org mode customization
survey. Mike McLean ran the survey in November 2013 using a [[https://github.com/SkydiveMike/org-customization-survey][collector
function]] provided by Carsten.

As of [2013-10-31 Thu], this is a placeholder only until the survey
results are received and tabulated.

** Contributors with abbreviations

The following people have sent in their customizations.

- MM - Mike McLean

** Notes

"Check email" - indicates a setting that is too long and/or personal
to be of general use.  Of course, it can still be accessed from email
by knowing the submitter and variable name.

"Same" means that the user has set the variables to its default,
probably because of playing with different values and the returning to
the default.  Such "customizations" have been taken out in the
statistical data, but they are still present in the raw data table.
