# Created 2021-06-15 Tue 18:23
#+TITLE: Mis-shapen chaos of well-seeming forms!
#+DATE: 1580
#+AUTHOR: Romeo
* To-address of the lovely Juliet :to:
Juliet
House of Capulet
Verona

* From :from:
House of Montague
Verona
* Location :location:
#+latex_header: \usepackage{tikz}
#+begin_center
*Montague*
#+end_center

* Dear Juliet,
#+begin_verse
Then plainly know my heart's dear love is set
On the fair daughter of rich Capulet:
As mine on hers, so hers is set on mine;
And all combin'd, save what thou must combine
By holy marriage: when, and where, and how
We met, we woo'd, and made exchange of vow,
I'll tell thee as we pass; but this I pray,
That thou consent to marry us to-day.
#+end_verse

* Yours truly, :closing:
Romeo of House Montague
* some arbitrary LaTeX code :my_after_signature:
* PS :ps:
PS: "PS" is not typeset automatically by KOMA-Script

 PPS: This is a feature!
* CC :cc:
Paris and Lawrence.
* ENCL :encl:
See also [[https://en.wikisource.org/wiki/The_Tragedy_of_Romeo_and_Juliet][The Tragedy of Romeo and Juliet]]
* some more arbitrary LaTeX code :after_letter:
