# Created 2021-06-15 Tue 18:20
#+OPTIONS: H:3 num:nil toc:2 \n:nil ::t |:t ^:{} -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+TITLE: Babel: active code in Org-mode
#+AUTHOR: Eric Schulte, Dan Davison, Tom Dye
#+startup: align fold nodlcheck hidestars oddeven lognotestate hideblocks
#+seq_todo: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+tags: Write(w) Update(u) Fix(f) Check(c) noexport(n)
#+language: en
#+html_link_home: https://orgmode.org/worg/
#+html_link_up: ../../index.html

Babel is Org-mode's ability to execute source code within Org-mode
documents.  If you are not familiar with Org-mode please take a moment
to read [[https://orgmode.org/][the Org-mode homepage]] before continuing.  Babel started life
as Org-babel, an extension to Org-mode.  It was integrated into the
Org-mode core at version 7.0. The author of Babel is Eric Schulte. The
secondary author is Dan Davison.

- [[https://www.jstatsoft.org/article/view/v046i03][A Multi-Language Computing Environment for Literate Programming and
  Reproducible Research]]: a journal paper providing the most up to date
  and complete introduction to using Org-mode and Babel for
  Reproducible research and literate programming.
- [[file:intro.org][Introductory Tutorial]]: a smaller online set of installation and
  setup instructions, as well as an overview of the main features of
  Babel, with plenty of examples.
- [[https://orgmode.org/manual/Working-with-Source-Code.html][Babel Documentation]]: is available in Chapter 15 of the Org-mode manual.
- [[file:languages/index.org][Language Support]]: a list of supported languages with information on
  requirements, configuration instructions, and language specific
  documentation.
- [[file:library-of-babel.org][Library of Babel]]: reusable source code blocks.
- [[file:uses.org][Uses]]: user-submitted examples of Babel work flows -- this is a good
  place to get an idea of what can be done and see how Babel may fit
  into your life.  In addition there is a collection of small code
  block examples and scraps at [[http://eschulte.github.io/org-scraps/][org-scraps]].

-----
