# Created 2021-06-15 Tue 18:24
#+TITLE: Org appearance
#+AUTHOR: Worg people
#+startup: align fold nodlcheck hidestars indent

[[file:index.org][{Back to Worg's index}]]

This page is about customizing the appearance of Org-mode.

* Customizing Org appearance
To customize all aspects of Org appearance use

#+begin_example
=M-x customize-group RET org-appearance RET=
#+end_example

Here you will find several options that can be chaged, and a further
link to a page for customizing [[id:f47abcd0-e31e-4b23-87db-d916d21665ad][Org-mode faces]].

** Customize Org-mode faces
A "face" is the term emacs uses to refer to the font and colour of
some text (as well as other features such as underlining etc).

Customizing Org faces is straightforward:

#+begin_example
=M-x customize-group RET org-faces RET=
#+end_example

You can also customize faces on the fly by just calling the
=customize-face= command with the cursor on the face you want to
customize.

** Hiding leading stars
the variable org-hide-leading-stars can be configured so that only
one star is shown at the start of each heading. Many people find
that this give the org buffer a cleaner appearance. This can be set
in the Org Font Lock customize group as explained above in
[[id:849d13ea-d2ca-45e8-ac49-ff7586c119cb][Customizing Org appearance]].

** Customizing the title, date, author and email lines.

The title, date and author information for an org document are
specified using the special keywords =#+TITLE:=, =#+DATE=,
=#+AUTHOR=, =#+EMAIL=.

By default, title, author, date and email lines appear in dark blue
with the initial keywords greyed out. The title is in a larger font
than the others. To change this, customize the faces

- org-document-title
- org-document-info
- org-document-info-keyword

In addition, the variable org-hidden-keywords can be used to make the
corresponding keywords disappear.

** Using only odd outline levels
The variable org-odd-levels-only can be used so that Org only uses
odd-numbered outline levels. Again, some people prefer this, finding
that the Org buffer looks less cluttered.

* Org-mode ready color-themes
Check out the list of [[file:../org-color-themes.org][color themes]] that are aware of org-mode.
